### ISSUE TITLE
bug: algorithm crash "could not broadcast input array"

### ISSUE THREAD

**Issue by garobrik** [techmatters/soil-id-algorithm#183]
### Site info
coordinates: `-104.0161438,44.7777328`
pedon key in test CSV file: `2340`

### traceback
```
Traceback (most recent call last):
  File "/home/roux/terraso/soil-id-algorithm/soil_id/tests/us/test_us.py", line 116, in test_with_real_data
    list_result = list_soils(lat=lat, lon=lon)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1098, in list_soils
    aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 256, in soil_sim
    simulate_correlated_triangular(
  File "/home/roux/terraso/soil-id-algorithm/soil_id/utils.py", line 1867, in simulate_correlated_triangular
    samples[condition, i] = a + np.sqrt(u[condition] * (c - a) * (b - a))
    ~~~~~~~^^^^^^^^^^^^^^
ValueError: could not broadcast input array from shape (1,10) into shape (1,3)
```

**Comment by DerekCaelin** [comment]
In v245, the Soil ID algorithm returns matches.
