### ISSUE TITLE
bug: algorithm crash "KeyError"

### ISSUE THREAD

**Issue by shrouxm** [techmatters/soil-id-algorithm#184]
### Coordinate to reproduce crash
`-121.4849972, 38.10115`
Pedon key in test CSV file: `71930`

### traceback
```
Traceback (most recent call last):
  File "/home/roux/terraso/soil-id-algorithm/soil_id/tests/us/test_us.py", line 116, in test_with_real_data
    list_result = list_soils(lat=lat, lon=lon)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1098, in list_soils
    aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 513, in soil_sim
    group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/.venv/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
    raise KeyError(name)
KeyError: 'kingile'
```

**Comment by garobrik** [comment]
This is still happening, here are some more examples:
```
Traceback #4, occurred 2 times. Example pedon: 8632, lat: 48.9713898, lon: -122.4402771
  Traceback (most recent call last):
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/tests/us/generate_bulk_test_results.py", line 53, in <module>
      lat = pedon["y"].values[0]
                        ~~~~~^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1121, in list_soils
      aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                           ~~~~~~~~^^^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 528, in soil_sim
      group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/.venv/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
      raise KeyError(name)
  KeyError: 'fishtrap'

Traceback #5, occurred 1 times. Example pedon: 6632, lat: 48.3329124, lon: -117.3235855
  Traceback (most recent call last):
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/tests/us/generate_bulk_test_results.py", line 53, in <module>
      lat = pedon["y"].values[0]
                        ~~~~~^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1121, in list_soils
      aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                           ~~~~~~~~^^^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 528, in soil_sim
      group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/.venv/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
      raise KeyError(name)
  KeyError: 'Belzar'

Traceback #6, occurred 1 times. Example pedon: 7091, lat: 35.98338, lon: -106.5964251
  Traceback (most recent call last):
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/tests/us/generate_bulk_test_results.py", line 53, in <module>
      lat = pedon["y"].values[0]
                        ~~~~~^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1121, in list_soils
      aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                           ~~~~~~~~^^^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 528, in soil_sim
      group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/.venv/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
      raise KeyError(name)
  KeyError: 'organic soils'

Traceback #7, occurred 1 times. Example pedon: 6857, lat: 46.3772888, lon: -124.0512543
  Traceback (most recent call last):
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/tests/us/generate_bulk_test_results.py", line 53, in <module>
      lat = pedon["y"].values[0]
                        ~~~~~^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1121, in list_soils
      aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                           ~~~~~~~~^^^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 528, in soil_sim
      group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/.venv/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
      raise KeyError(name)
  KeyError: 'seastrand'

Traceback #8, occurred 1 times. Example pedon: 3054, lat: 38.9052773, lon: -119.8233337
  Traceback (most recent call last):
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/tests/us/generate_bulk_test_results.py", line 53, in <module>
      lat = pedon["y"].values[0]
                        ~~~~~^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1121, in list_soils
      aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                           ~~~~~~~~^^^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 528, in soil_sim
      group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/.venv/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
      raise KeyError(name)
  KeyError: 'shalpeet'

Traceback #9, occurred 1 times. Example pedon: 8638, lat: 48.9788895, lon: -122.3916702
  Traceback (most recent call last):
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/tests/us/generate_bulk_test_results.py", line 53, in <module>
      lat = pedon["y"].values[0]
                        ~~~~~^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1121, in list_soils
      aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                           ~~~~~~~~^^^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 528, in soil_sim
      group_df1 = groups1.get_group(group_label).reset_index(drop=True)
                  ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
    File "/home/roux/projects/terraso/soil-id-algorithm/.venv/lib/python3.13/site-packages/pandas/core/groupby/groupby.py", line 1114, in get_group
      raise KeyError(name)
  KeyError: 'shalcar'
```

**Comment by garobrik** [comment]
@DerekCaelin FYI: based on local testing and what I see in sentry on production (it happens semi-regularly, not sure how many of them are us testing), I would say this is definitely the highest prio algorithm crash.

**Comment by DerekCaelin** [comment]
Issue resolves on staging, build 351
