### ISSUE TITLE
bug: algorithm crash "AttributeError"

### ISSUE THREAD

**Issue by garobrik** [techmatters/soil-id-algorithm#185]
### Site info
coordinate: `-121.2375031, 47.3597221`
pedon key in test CSV: `19922`

### traceback
```
Traceback (most recent call last):
  File "/home/roux/terraso/soil-id-algorithm/soil_id/tests/us/test_us.py", line 118, in test_with_real_data
    result_record["rank_result"] = rank_soils(
                                   ^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1694, in rank_soils
    soilIDRank_output_pd = pd.read_csv(io.StringIO(list_output_data.rank_data_csv))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'rank_data_csv'
```

**Comment by garobrik** [comment]
can't reproduce (algorithm correctly determines that data is unavailable because coordinate is in a body of water)
