### ISSUE TITLE
bug: algorithm crash "ValueError: No objects to concatenate"

### ISSUE THREAD

**Issue by shrouxm** [techmatters/soil-id-algorithm#187]
### Site info
Coordinates: `-121.5111084, 45.6508331`
Pedon key in test file: `818`

### traceback
```
Traceback (most recent call last):
  File "/home/roux/terraso/soil-id-algorithm/soil_id/tests/us/test_us.py", line 116, in test_with_real_data
    list_result = list_soils(lat=lat, lon=lon)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/us_soil.py", line 1098, in list_soils
    aws_PIW90, var_imp = soil_sim(muhorzdata_pd)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/soil_id/soil_sim.py", line 127, in soil_sim
    agg_data_df = pd.concat(agg_data, axis=0, ignore_index=True).dropna().reset_index(drop=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/.venv/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/.venv/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/roux/terraso/soil-id-algorithm/.venv/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

**Comment by DerekCaelin** [comment]
in v245, Soil ID algorithm returns matches
